import { Trip, Traveler, Expense, Photo, Reservation } from './types'

export const mockTravelers: Traveler[] = [
  { 
    id: '1', 
    name: 'Alex Chen', 
    email: 'alex@email.com',
    color: '#E85D4C', 
    isOnline: true,
    role: 'organizer',
    rsvpStatus: 'going',
    joinedAt: '2026-03-01'
  },
  { 
    id: '2', 
    name: 'Sarah Miller', 
    email: 'sarah@email.com',
    color: '#3D9A7D', 
    isOnline: true,
    role: 'editor',
    rsvpStatus: 'going',
    joinedAt: '2026-03-02'
  },
  { 
    id: '3', 
    name: 'James Wilson', 
    email: 'james@email.com',
    color: '#D4A853', 
    isOnline: false,
    role: 'editor',
    rsvpStatus: 'maybe',
    joinedAt: '2026-03-05'
  },
  { 
    id: '4', 
    name: 'Emma Davis', 
    email: 'emma@email.com',
    color: '#7C5CBF', 
    isOnline: false,
    role: 'viewer',
    rsvpStatus: 'pending',
    joinedAt: '2026-03-10'
  },
]

export const mockExpenses: Expense[] = [
  {
    id: 'exp-1',
    description: 'Park Hyatt Tokyo - 3 nights',
    amount: 1350,
    currency: 'USD',
    paidBy: '1',
    splitWith: ['1', '2', '3'],
    splitType: 'equal',
    category: 'lodging',
    date: '2026-06-15',
    settled: false,
  },
  {
    id: 'exp-2',
    description: 'Group dinner at Gonpachi',
    amount: 180,
    currency: 'USD',
    paidBy: '2',
    splitWith: ['1', '2', '3'],
    splitType: 'equal',
    category: 'food',
    date: '2026-06-16',
    settled: false,
  },
  {
    id: 'exp-3',
    description: 'TeamLab tickets',
    amount: 105,
    currency: 'USD',
    paidBy: '3',
    splitWith: ['1', '2', '3'],
    splitType: 'equal',
    category: 'activities',
    date: '2026-06-17',
    settled: true,
  },
  {
    id: 'exp-4',
    description: 'Airport limousine bus',
    amount: 90,
    currency: 'USD',
    paidBy: '1',
    splitWith: ['1', '2', '3'],
    splitType: 'equal',
    category: 'transport',
    date: '2026-06-15',
    settled: false,
  },
  {
    id: 'exp-5',
    description: 'Convenience store snacks',
    amount: 25,
    currency: 'USD',
    paidBy: '2',
    splitWith: ['1', '2'],
    splitType: 'equal',
    category: 'food',
    date: '2026-06-16',
    settled: true,
  },
]

export const mockPhotos: Photo[] = [
  {
    id: 'photo-1',
    url: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200',
    thumbnailUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400',
    uploadedBy: '1',
    uploadedAt: '2026-06-15T18:30:00Z',
    caption: 'Tokyo Tower at sunset',
    dayId: 'day-1',
    likes: ['2', '3'],
  },
  {
    id: 'photo-2',
    url: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200',
    thumbnailUrl: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=400',
    uploadedBy: '2',
    uploadedAt: '2026-06-16T10:15:00Z',
    caption: 'Senso-ji Temple entrance',
    dayId: 'day-2',
    placeId: 'place-4',
    likes: ['1', '3'],
  },
  {
    id: 'photo-3',
    url: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200',
    thumbnailUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=400',
    uploadedBy: '3',
    uploadedAt: '2026-06-16T15:45:00Z',
    caption: 'Shibuya crossing chaos',
    dayId: 'day-2',
    placeId: 'place-6',
    likes: ['1', '2'],
  },
  {
    id: 'photo-4',
    url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200',
    thumbnailUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=400',
    uploadedBy: '1',
    uploadedAt: '2026-06-17T11:20:00Z',
    caption: 'TeamLab was incredible',
    dayId: 'day-3',
    placeId: 'place-8',
    likes: ['2', '3'],
  },
  {
    id: 'photo-5',
    url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=400',
    uploadedBy: '2',
    uploadedAt: '2026-06-17T14:30:00Z',
    caption: 'Fresh sushi at Tsukiji',
    dayId: 'day-3',
    placeId: 'place-9',
    likes: ['1'],
  },
  {
    id: 'photo-6',
    url: 'https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200',
    thumbnailUrl: 'https://images.unsplash.com/photo-1480796927426-f609979314bd?w=400',
    uploadedBy: '3',
    uploadedAt: '2026-06-16T19:00:00Z',
    caption: 'Night view from hotel',
    dayId: 'day-2',
    likes: ['1', '2'],
  },
]

export const mockReservations: Reservation[] = [
  {
    id: 'res-1',
    type: 'flight',
    name: 'United Airlines UA837',
    confirmationNumber: 'ABC123',
    startDate: '2026-06-15',
    startTime: '10:30',
    endTime: '14:00',
    cost: 850,
    currency: 'USD',
    bookedBy: '1',
    travelers: ['1', '2', '3'],
    notes: 'SFO to NRT, Economy Plus',
    status: 'confirmed',
  },
  {
    id: 'res-2',
    type: 'hotel',
    name: 'Park Hyatt Tokyo',
    confirmationNumber: 'HYT789456',
    startDate: '2026-06-15',
    endDate: '2026-06-18',
    startTime: '15:00',
    location: { lat: 35.6855, lng: 139.6907, address: '3-7-1-2 Nishi Shinjuku' },
    cost: 1350,
    currency: 'USD',
    bookedBy: '1',
    travelers: ['1', '2', '3'],
    notes: 'Deluxe room with city view',
    status: 'confirmed',
  },
  {
    id: 'res-3',
    type: 'activity',
    name: 'TeamLab Borderless',
    confirmationNumber: 'TL2026061700123',
    startDate: '2026-06-17',
    startTime: '10:00',
    location: { lat: 35.6262, lng: 139.7834, address: 'Odaiba' },
    cost: 105,
    currency: 'USD',
    bookedBy: '2',
    travelers: ['1', '2', '3'],
    notes: 'Timed entry - arrive 15 min early',
    status: 'confirmed',
  },
  {
    id: 'res-4',
    type: 'restaurant',
    name: 'Gonpachi Nishi-Azabu',
    confirmationNumber: 'GP0616-1900',
    startDate: '2026-06-16',
    startTime: '19:00',
    location: { lat: 35.6568, lng: 139.7232, address: '1-13-11 Nishi-Azabu' },
    bookedBy: '3',
    travelers: ['1', '2', '3'],
    notes: 'Table for 3, requested tatami seating',
    status: 'confirmed',
  },
  {
    id: 'res-5',
    type: 'flight',
    name: 'United Airlines UA838',
    confirmationNumber: 'ABC124',
    startDate: '2026-06-22',
    startTime: '17:00',
    endTime: '11:30',
    cost: 820,
    currency: 'USD',
    bookedBy: '1',
    travelers: ['1', '2', '3'],
    notes: 'NRT to SFO, Economy Plus',
    status: 'confirmed',
  },
]

export const mockTrip: Trip = {
  id: 'trip-1',
  name: 'Japan Adventure',
  destination: 'Tokyo, Japan',
  description: 'A week exploring Tokyo, from ancient temples to futuristic art installations.',
  startDate: '2026-06-15',
  endDate: '2026-06-22',
  coverImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1600',
  createdBy: '1',
  travelers: mockTravelers,
  expenses: mockExpenses,
  photos: mockPhotos,
  reservations: mockReservations,
  days: [
    {
      id: 'day-1',
      date: '2026-06-15',
      places: [
        {
          id: 'place-1',
          name: 'Narita International Airport',
          type: 'transport',
          location: { lat: 35.7647, lng: 140.3864, address: 'Narita, Chiba' },
          time: '14:00',
          notes: 'Flight JL001 arrives',
          votes: { up: ['1', '2'], down: [] },
          addedBy: '1',
          booked: true,
        },
        {
          id: 'place-2',
          name: 'Park Hyatt Tokyo',
          type: 'accommodation',
          location: { lat: 35.6855, lng: 139.6907, address: '3-7-1-2 Nishi Shinjuku' },
          time: '16:00',
          cost: 450,
          currency: 'USD',
          notes: 'Check-in from 3PM',
          votes: { up: ['1', '2', '3'], down: [] },
          addedBy: '2',
          booked: true,
          bookingUrl: 'https://www.hyatt.com',
          imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600',
        },
        {
          id: 'place-3',
          name: 'Ichiran Ramen Shinjuku',
          type: 'restaurant',
          location: { lat: 35.6938, lng: 139.7034, address: 'Shinjuku Station Area' },
          time: '19:30',
          duration: '1h',
          cost: 15,
          currency: 'USD',
          votes: { up: ['1', '3'], down: ['2'] },
          addedBy: '3',
          imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600',
        },
      ],
    },
    {
      id: 'day-2',
      date: '2026-06-16',
      places: [
        {
          id: 'place-4',
          name: 'Senso-ji Temple',
          type: 'landmark',
          location: { lat: 35.7148, lng: 139.7967, address: '2-3-1 Asakusa, Taito' },
          time: '09:00',
          duration: '2h',
          votes: { up: ['1', '2', '3'], down: [] },
          addedBy: '1',
          imageUrl: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=600',
        },
        {
          id: 'place-5',
          name: 'Tokyo Skytree',
          type: 'activity',
          location: { lat: 35.7101, lng: 139.8107, address: '1-1-2 Oshiage, Sumida' },
          time: '12:00',
          duration: '1.5h',
          cost: 25,
          currency: 'USD',
          votes: { up: ['2'], down: ['1'] },
          addedBy: '2',
          bookingUrl: 'https://www.tokyo-skytree.jp',
          imageUrl: 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=600',
        },
        {
          id: 'place-6',
          name: 'Shibuya Crossing',
          type: 'landmark',
          location: { lat: 35.6595, lng: 139.7004, address: 'Shibuya Station' },
          time: '15:00',
          duration: '30m',
          votes: { up: ['1', '2', '3'], down: [] },
          addedBy: '1',
          imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600',
        },
        {
          id: 'place-7',
          name: 'Gonpachi Nishi-Azabu',
          type: 'restaurant',
          location: { lat: 35.6568, lng: 139.7232, address: '1-13-11 Nishi-Azabu' },
          time: '19:00',
          duration: '2h',
          cost: 60,
          currency: 'USD',
          notes: 'Kill Bill restaurant - reservation confirmed',
          votes: { up: ['1', '2'], down: [] },
          addedBy: '3',
          booked: true,
          imageUrl: 'https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=600',
        },
      ],
    },
    {
      id: 'day-3',
      date: '2026-06-17',
      places: [
        {
          id: 'place-8',
          name: 'TeamLab Borderless',
          type: 'activity',
          location: { lat: 35.6262, lng: 139.7834, address: 'Odaiba' },
          time: '10:00',
          duration: '3h',
          cost: 35,
          currency: 'USD',
          notes: 'Tickets pre-booked',
          votes: { up: ['1', '2', '3'], down: [] },
          addedBy: '2',
          booked: true,
          bookingUrl: 'https://borderless.teamlab.art',
          imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600',
        },
        {
          id: 'place-9',
          name: 'Tsukiji Outer Market',
          type: 'activity',
          location: { lat: 35.6654, lng: 139.7707, address: 'Tsukiji 4-chome' },
          time: '14:00',
          duration: '2h',
          votes: { up: ['1', '3'], down: [] },
          addedBy: '1',
          imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=600',
        },
      ],
    },
    {
      id: 'day-4',
      date: '2026-06-18',
      places: [
        {
          id: 'place-10',
          name: 'Meiji Shrine',
          type: 'landmark',
          location: { lat: 35.6764, lng: 139.6993, address: '1-1 Yoyogikamizonocho' },
          time: '08:00',
          duration: '1.5h',
          votes: { up: ['1', '2'], down: [] },
          addedBy: '2',
        },
        {
          id: 'place-11',
          name: 'Harajuku and Takeshita Street',
          type: 'activity',
          location: { lat: 35.6715, lng: 139.7030, address: 'Harajuku Station' },
          time: '10:30',
          duration: '2h',
          votes: { up: ['2', '3'], down: [] },
          addedBy: '3',
        },
      ],
    },
    {
      id: 'day-5',
      date: '2026-06-19',
      places: [],
    },
    {
      id: 'day-6',
      date: '2026-06-20',
      places: [],
    },
    {
      id: 'day-7',
      date: '2026-06-21',
      places: [],
    },
    {
      id: 'day-8',
      date: '2026-06-22',
      places: [
        {
          id: 'place-12',
          name: 'Narita International Airport',
          type: 'transport',
          location: { lat: 35.7647, lng: 140.3864, address: 'Narita, Chiba' },
          time: '15:00',
          notes: 'Flight departs 17:00',
          votes: { up: ['1', '2', '3'], down: [] },
          addedBy: '1',
          booked: true,
        },
      ],
    },
  ],
}

// Helper to calculate balances
export function calculateBalances(travelers: Traveler[], expenses: Expense[]): Map<string, { owes: Map<string, number>, owed: Map<string, number>, net: number }> {
  const balances = new Map<string, { owes: Map<string, number>, owed: Map<string, number>, net: number }>()
  
  travelers.forEach(t => {
    balances.set(t.id, { owes: new Map(), owed: new Map(), net: 0 })
  })
  
  expenses.forEach(expense => {
    if (expense.splitType === 'equal') {
      const splitAmount = expense.amount / expense.splitWith.length
      expense.splitWith.forEach(userId => {
        if (userId !== expense.paidBy) {
          const payer = balances.get(expense.paidBy)!
          const debtor = balances.get(userId)!
          
          payer.owed.set(userId, (payer.owed.get(userId) || 0) + splitAmount)
          payer.net += splitAmount
          
          debtor.owes.set(expense.paidBy, (debtor.owes.get(expense.paidBy) || 0) + splitAmount)
          debtor.net -= splitAmount
        }
      })
    }
  })
  
  return balances
}
